# Generated by Django 3.2.4 on 2021-07-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_replycomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='replycomment',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
