# Generated by Django 3.2.4 on 2021-07-05 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_replycomment_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replycomment',
            old_name='data',
            new_name='date',
        ),
    ]
