# Generated by Django 3.2.4 on 2021-07-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_data_replycomment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tag_list',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
