# Generated by Django 3.2.4 on 2021-06-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_contact_number_number_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='delivery_address',
            field=models.TextField(blank=True, default='None', null=True),
        ),
    ]
