# Generated by Django 3.2.4 on 2021-07-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_custom_user_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_banner',
            name='image',
            field=models.FileField(default='homebanner.jpg', upload_to='home_banner'),
        ),
    ]
