# Generated by Django 3.1.7 on 2021-07-07 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20210707_1702'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
