# Generated by Django 3.2.4 on 2021-07-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_order_cart_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart_ids',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
