# Generated by Django 3.1.7 on 2021-07-07 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210707_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_paid',
            new_name='confirm',
        ),
    ]
