# Generated by Django 3.1.7 on 2021-07-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210707_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tran_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
